version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  parallel: true
  verbosity: minimal