version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
# before_build:
# - ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
- path: src\NetEx\System.Windows.Forms.ProgressDialog\bin\Release\System.Windows.Forms.ProgressDialog.dll
  name: System.Windows.Forms.ProgressDialog.dll
deploy:
- provider: NuGet
  api_key:
    secure: f61AuiPjK/d/mSrOUwrlm5xCsm2wQy6dSvctx0i+4cflNYI9HZO3Fes2X0Q0oZmo
  skip_symbols: true
