version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
# before_build:
# - ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\Release\System.Windows.Forms.ProgressDialog.dll
  name: System.Windows.Forms.ProgressDialog.dll
- path: bin\Release\NetExDemo.exe
  name: NetExDemo.exe
deploy:
- provider: NuGet
  api_key:
    secure: lp4jynubZ3xe3mEnGZVCb68/tWmL/W0w4phOKXTCJfquR4RMnugHxrjGDD4EiWK5
  skip_symbols: true
- provider: GitHub
  auth_token:
    secure: isEFYOVaEKqlpeedx1hkwBRLJmJ203QY5aD78YjoJMkTRE06axrX48fPfXNP5BNu
  artifact: System.Windows.Forms.ProgressDialog.dll,NetExDemo.exe
  draft: true
