using System.Runtime.InteropServices;

namespace NetEx.Hooks.Interop
{
    /// <summary>
    /// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
    /// </summary>
    /// <seealso href="https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-hardwareinput"/>
    [StructLayout(LayoutKind.Sequential)]
    internal struct HARDWAREINPUT
    {
        #region Fields

        /// <summary>
        /// The message generated by the input hardware.
        /// </summary>
        public uint uMsg;
        /// <summary>
        /// The low-order word of the lParam parameter for uMsg.
        /// </summary>
        public ushort wParamL;
        /// <summary>
        /// The high-order word of the lParam parameter for uMsg.
        /// </summary>
        public ushort wParamH;

        #endregion
    }
}