name: Build Libraries

on:
  workflow_call:
    inputs:
      BUILD_CONFIGURATION:
        type: string
      DOTNET_VERSION:
        type: string

jobs:

  Build:
    runs-on: windows-latest

    steps:
    
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.DOTNET_VERSION }}

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore
      working-directory: src

    # Build the project
    - name: Build
      run: |
        dotnet build NetEx.Dialogs.WinForms/NetEx.Dialogs.WinForms.csproj --configuration ${{ inputs.BUILD_CONFIGURATION }} --no-restore
        dotnet build NetEx.Hooks/NetEx.Hooks.csproj --configuration ${{ inputs.BUILD_CONFIGURATION }} --no-restore
        dotnet build NetEx.IO/NetEx.IO.csproj --configuration ${{ inputs.BUILD_CONFIGURATION }} --no-restore
      working-directory: src
          
    # Upload build artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nupkg-files
        path: src/**/*.nupkg