name: build

on:
  pull_request:
    branches: [ "main" ]
#  release:
#    types: [published]

env:
  DOTNET_VERSION: '9.0.x'
  WORKING_DIRECTORY: 'src/NetEx.CredentialDialog'

jobs:

  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
    - uses: actions/checkout@v4

    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}

    # Build the project
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY }}


