name: Build Library

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
  push:
    branches:
      - main
    paths:
      - src/**
  release:
    types: [published]
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 9.0.x

jobs:

  Build:
    runs-on: windows-latest

    steps:
    
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore
      working-directory: src

    # Build the project
    - name: Build
      run: |
        dotnet build NetEx.WinForms.CredentialDialog/NetEx.WinForms.CredentialDialog.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build NetEx.WinForms.ProgressDialog/NetEx.WinForms.ProgressDialog.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      working-directory: src

    # Update DocFX tool
    - name: Update DocFX
      run: dotnet tool update -g docfx
    
    # Generate documentation
    - name: Generate Documentation
      run: docfx docfx.json
      working-directory: docs
          
    # Upload build artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nupkg-files
        path: src/**/*.nupkg

    # Upload documentation artifacts
    - name: Upload Documentation Artifacts
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_site/
      
  Deploy:
    runs-on: windows-latest
    needs: Build
    permissions:
      contents: write
      id-token: write
      pages: write
    if: github.event_name == 'release'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
        
    # Download build artifacts
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: nupkg-files

    # Publish the build packages to NuGet
    #- name: Publish to NuGet
    #  run: dotnet publish --configuration Release --output ./output

    # Upload the build output to the release
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./**/*.nupkg

    # Upload documentation to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4