name: Build Library

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  push:
    branches:
      - main
    paths:
      - 'src/**'
  release:
    types: [published]
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: 'Release'
  DOTNET_VERSION: '9.0.x'
  #WORKING_DIRECTORY: 'src/NetEx.WinForms.ProgressDialog'

jobs:

  Build:
    runs-on: windows-latest

    steps:
    
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore
      #working-directory: ${{ env.WORKING_DIRECTORY }}

    # Build the project
    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      #working-directory: ${{ env.WORKING_DIRECTORY }}

    # Update DocFX tool
    - name: Update DocFX
      run: dotnet tool update -g docfx
    
    # Generate documentation
    - name: Generate Documentation
      run: docfx ../docs/docfx.json

    # Publish the build output
    #- name: Publish
    #  if: github.event_name == 'release'
    #  run: dotnet publish --configuration Release --output ./output

    # Conditionally upload the build output to the release
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: '**/*.nupkg'