name: Build

on:
  pull_request:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  WORKING_DIRECTORY: 'src/NetEx.WinForms.ProgressDialog'

jobs:

  Build:
    runs-on: windows-latest

    steps:
    
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}

    # Build the project
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY }}

    # Run test projects - No tests at present
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

    # Publish the build output
    #- name: Publish
    #  run: dotnet publish --configuration Release --output ./output

    # Conditionally upload the build output to the release
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./output
        asset_name: build-output.zip
        asset_content_type: application/zip
