name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 9.0.x

jobs:

  Build:
    uses: ./.github/workflows/build-libraries.yml
    with:
      BUILD_CONFIGURATION: ${{ env.BUILD_CONFIGURATION }}
      DOTNET_VERSION: ${{ env.DOTNET_VERSION }}