name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 9.0.x

jobs:

  Build:
    uses: ./.github/workflows/build-library.yml
      
  Documentation:
    uses: ./.github/workflows/publish-documentation.yml
