name: Release

on:
  #release:
  #  types: [published]
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 9.0.x

jobs:

  Build:
    uses: ./.github/workflows/build-library.yml
    with:
      BUILD_CONFIGURATION: Release
      DOTNET_VERSION: ${{ env.DOTNET_VERSION }}

  Publish:
    runs-on: windows-latest
    needs: Build

    steps:
        
    # Download build artifacts
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: nupkg-files

    # Upload the build output to the release
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./**/*.nupkg

    # Publish the build packages to NuGet
    #- name: Publish to NuGet
    #  env:
    #    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    #  run: |
    #    dotnet nuget push ./**/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

  Documentation:
    needs: Publish
    uses: ./.github/workflows/publish-documentation.yml
    with:
      DOTNET_VERSION: ${{ env.DOTNET_VERSION }}